# Generated by Django 4.2.11 on 2025-02-28 14:31

from django.db import migrations


def add_rdf_resource_type(apps, schema_editor):
    Resource = apps.get_model("resource", "Resource")
    ResourceType = apps.get_model("resource", "ResourceType")
    AllocationAttributeType = apps.get_model("allocation", "AllocationAttributeType")
    AttributeType = apps.get_model("allocation", "AttributeType")

    storage_resource_type, _ = ResourceType.objects.get_or_create(
        name="Storage",
        defaults=dict(description="NAS storage"),
    )
    Resource.objects.get_or_create(
        name="RDF Active",
        defaults=dict(
            description="Storage space associated with a research group on the RDF.",
            is_allocatable=True,
            is_available=True,
            is_public=True,
            requires_payment=False,
            resource_type=storage_resource_type,
        ),
    )

    text_attribute_type, _ = AttributeType.objects.get_or_create(name="Text")
    AllocationAttributeType.objects.get_or_create(
        name="RDF Project ID",
        defaults=dict(
            attribute_type=text_attribute_type,
            is_unique=True,
            is_private=True,
            is_changeable=False,
        ),
    )

    AllocationAttributeType.objects.get_or_create(
        name="DART ID",
        defaults=dict(
            attribute_type=text_attribute_type,
            is_unique=False,
            is_changeable=False,
            is_private=False,
        ),
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resource", "0002_auto_20191017_1141"),
        ("allocation", "0005_auto_20211117_1413"),
    ]

    operations = [
        migrations.RunPython(add_rdf_resource_type),
    ]
