# Generated by Django 4.2.11 on 2025-04-01 10:22

from django.db import migrations
import datetime
from django_q.tasks import schedule


def run_consistency_check(apps, schema_editor):
    """Schedule a task to run the consistency check."""
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.update_or_create(
        name="LDAP consistency check",
        func="imperial_coldfront_plugin.ldap.check_ldap_consistency",
        schedule_type="D",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0001_add_rdf_resource_rdf_project_attribute_dart_id_attribute'),
        ('django_q', '0014_schedule_cluster'),
    ]

    operations = [
        migrations.RunPython(run_consistency_check),
    ]
