# Generated by Django 4.2.11 on 2025-05-08 21:58

from django.db import migrations

def schedule_update_quota_usages_task(apps, schema_editor):
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.update_or_create(
        name="Update quota usages",
        func="imperial_coldfront_plugin.gpfs_client._update_quota_usages_task",
        schedule_type="H",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0002_schedule_ldap_consistency_check'),
    ]

    operations = [
        migrations.RunPython(schedule_update_quota_usages_task),
    ]
