# Generated by Django 4.2.11 on 2025-01-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0003_remove_groupmembership_owner_researchgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
