# Generated by Django 4.2.11 on 2025-01-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0004_alter_groupmembership_member_alter_unixuid_user'),
        ('imperial_coldfront_plugin', '0004_groupmembership_is_manager'),
    ]

    operations = [
    ]
