# Generated by Django 4.2.11 on 2025-01-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0004_alter_groupmembership_member_alter_unixuid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
