# Generated by Django 4.2.11 on 2025-01-23 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0005_groupmembership_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
            preserve_default=False,
        ),
    ]
