# Generated by Django 4.2.11 on 2025-06-08 17:00

from django.db import migrations


def add_files_quota_attribute(apps, schema_editor):
    AllocationAttributeType = apps.get_model("allocation", "AllocationAttributeType")
    AttributeType = apps.get_model("allocation", "AttributeType")

    int_attribute_type, _ = AttributeType.objects.get_or_create(name="Int")
    AllocationAttributeType.objects.get_or_create(
        name="Storage Quota (TB)",
        defaults=dict(
            attribute_type=int_attribute_type,
            is_unique=True,
            is_private=False,
            is_changeable=False,
        )
    )

class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0005_add_files_quota_attribute'),
        ("allocation", "0005_auto_20211117_1413"),
    ]

    operations = [
        migrations.RunPython(add_files_quota_attribute)
    ]
