# Generated by Django 4.2.11 on 2025-01-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0005_groupmembership_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='expiration',
            field=models.DateTimeField(null=True),
        ),
    ]
