# Generated by Django 4.2.11 on 2025-08-26 14:52

from django.db import migrations


def add_shortname_attribute(apps, schema_editor):
    AllocationAttributeType = apps.get_model("allocation", "AllocationAttributeType")
    AttributeType = apps.get_model("allocation", "AttributeType")

    text_attribute_type, _ = AttributeType.objects.get_or_create(name="Text")
    AllocationAttributeType.objects.get_or_create(
        name="Shortname",
        defaults=dict(
            attribute_type=text_attribute_type,
            is_unique=True,
            is_private=False,
            is_changeable=False,
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0006_add_storage_quota_tb_attribute'),
        ("allocation", "0005_auto_20211117_1413"),
    ]

    operations = [
        migrations.RunPython(add_shortname_attribute)
    ]
