# Generated by Django 4.2.11 on 2025-01-23 15:47

from django.db import migrations


def add_group_pruning_task(apps, schema_editor):
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.update_or_create(
        name="Prune Expired Group Memberships",
        func="django.core.management.call_command",
        args=["prune_groups"],
        schedule_type="D",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("imperial_coldfront_plugin", "0006_groupmembership_expiration"),
    ]

    operations = [
        # migrations.RunPython(add_group_pruning_task),  # This line is commented out because the group pruning task is currently not required. Uncomment if needed in the future.
    ]
