# Generated by Django 4.2.11 on 2025-02-12 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imperial_coldfront_plugin', '0007_groupmembership_pruning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
