# Generated by Django 4.2.11 on 2025-09-04 14:34

from django.db import migrations

def add_allocation_location_attribute(apps, schema_editor):
    AllocationAttributeType = apps.get_model("allocation", "AllocationAttributeType")
    AttributeType = apps.get_model("allocation", "AttributeType")

    text_attribute_type, _ = AttributeType.objects.get_or_create(name="Text")
    AllocationAttributeType.objects.get_or_create(
        name="Filesystem location",
        defaults=dict(
            attribute_type=text_attribute_type,
            is_unique=True,
            is_private=False,
            is_changeable=False,
            is_required=False,
        )
    )

class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0008_project_attributes'),
        ("allocation", "0005_auto_20211117_1413"),
    ]

    operations = [
        migrations.RunPython(add_allocation_location_attribute)
    ]
