# Generated by Django 4.2.11 on 2025-09-15 16:44

from django.db import migrations


def add_project_ticket_attribute(apps, schema_editor):
    ProjectAttributeType = apps.get_model("project", "ProjectAttributeType")
    AttributeType = apps.get_model("project", "AttributeType")

    text_attribute_type, _ = AttributeType.objects.get_or_create(name="Text")
    ProjectAttributeType.objects.get_or_create(
        name="ASK Ticket Reference",
        defaults=dict(
            attribute_type=text_attribute_type,
            is_unique=True,
            is_private=False,
            is_changeable=False,
            is_required=False,
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0009_allocation_location_attribute'),
        ('project', '0004_auto_20230406_1133'),
    ]

    operations = [
        migrations.RunPython(add_project_ticket_attribute)
    ]
