# Generated by Django 4.2.11 on 2025-04-01 10:22

from django.db import migrations
import datetime
from django_q.tasks import schedule

def run_consistency_check():
    """Run the LDAP consistency check task."""
    schedule(
        "imperial_coldfront_plugin.ldap.check_ldap_consistency",
        schedule_type="D",
        repeats=-1,
        next_run= datetime.datetime.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0010_auto_20250228_1431'),
    ]

    operations = [
        migrations.RunPython(run_consistency_check),
    ]
