# Generated by Django 4.2.11 on 2025-05-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0011_auto_20250401_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnixUID',
        ),
    ]
