# Generated by Django 4.2.11 on 2026-01-30 14:36

from django.db import migrations


def create_expiry_notification_schedule(apps, schema_editor):
    """Create scheduled task for RDF allocation expiry notifications."""
    Schedule = apps.get_model("django_q", "Schedule")

    Schedule.objects.get_or_create(
        func="imperial_coldfront_plugin.tasks.check_rdf_allocation_expiry_notifications",
        defaults={
            "name": "RDF Allocation Expiry Notifications",
            "schedule_type": "D",  # Daily
            "repeats": -1,  # Run indefinitely
        },
    )


def delete_expiry_notification_schedule(apps, schema_editor):
    """Remove scheduled task for RDF allocation expiry notifications."""
    Schedule = apps.get_model("django_q", "Schedule")

    Schedule.objects.filter(
        func="imperial_coldfront_plugin.tasks.check_rdf_allocation_expiry_notifications"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0011_initial'),
        ('django_q', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            create_expiry_notification_schedule,
            reverse_code=delete_expiry_notification_schedule,
        ),
    ]
