# Generated by Django 4.2.11 on 2026-01-28 11:36

from django.db import migrations


def add_deleted_allocation_status(apps, schema_editor):
    """Add "deleted" as an AllocationStatusChoice instance."""
    AllocationStatusChoice = apps.get_model("allocation", "AllocationStatusChoice")
    AllocationStatusChoice.objects.get_or_create(
        name="Deleted",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0011_initial'),
    ]

    operations = [
        migrations.RunPython(add_deleted_allocation_status)
    ]
