# Generated by Django 4.2.11 on 2026-02-02 10:54

from django.db import migrations

def schedule_check_of_allocation_status(apps, schema_editor):
    """Adds a scheduled task to check if any allocations should be marked as deleted."""
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.update_or_create(
        name="Change allocation status to deleted for expired allocations",
        func="imperial_coldfront_plugin.tasks.mark_expired_allocations_as_deleted",
        schedule_type="D",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0012_auto_20260128_1136'),
    ]

    operations = [
        migrations.RunPython(schedule_check_of_allocation_status)
    ]
