# Generated by Django 4.2.11 on 2026-02-02 17:15

from django.db import migrations

def add_removed_and_deleted_allocation_status(apps, schema_editor):
    """Add "removed" and "deleted" as an AllocationStatusChoice instance."""
    AllocationStatusChoice = apps.get_model("allocation", "AllocationStatusChoice")
    AllocationStatusChoice.objects.get_or_create(
        name="Deleted",
    )
    AllocationStatusChoice.objects.get_or_create(
        name="Removed"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0012_schedule_rdf_allocation_expiry'),
    ]

    operations = [
        migrations.RunPython(add_removed_and_deleted_allocation_status)
    ]
