# Generated by Django 4.2.11 on 2026-02-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0012_schedule_rdf_allocation_expiry'),
        ('imperial_coldfront_plugin', '0013_auto_20260202_1054'),
    ]

    operations = [
    ]
