# Generated by Django 4.2.11 on 2026-02-02 17:20

from django.db import migrations


def schedule_check_allocation_status(apps, schema_editor):
    """Adds scheduled task to check if any allocations should be marked as removed or deleted."""
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.update_or_create(
        name="Change allocation status to deleted or removed for expired allocations",
        func="imperial_coldfront_plugin.tasks.check_allocation_status",
        schedule_type="D",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0013_add_deleted_and_removed_status'),
    ]

    operations = [
        migrations.RunPython(schedule_check_allocation_status)
    ]
