# Generated by Django 4.2.11 on 2025-05-08 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0013_auto_20250508_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchgroup',
            name='owner',
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
        migrations.DeleteModel(
            name='ResearchGroup',
        ),
    ]
