# Generated by Django 4.2.11 on 2026-02-04 17:08

from django.db import migrations

def create_schedule(apps, schema_editor):
    """Re-create the schedule for rollback purposes."""
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.get_or_create(
        name="Check for expired allocations and set GPFS quota to zero",
        func="imperial_coldfront_plugin.tasks.expired_allocations_gpfs_quota_check",
        schedule_type="D",
        repeats=-1,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0014_schedule_allocation_status_check'),
        ('django_q', '0014_schedule_cluster'),
    ]

    operations = [
        migrations.RunPython(create_schedule),
    ]
