# Generated by Django 4.2.11 on 2026-02-10 20:38

from django.db import migrations


def schedule_check_quota_consistency(apps, schema_editor):
    """Adds scheduled task to check if any quotas are inconsistent."""
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.update_or_create(
        name="Check quota consistency between Coldfront and GPFS",
        func="imperial_coldfront_plugin.tasks.check_quota_consistency",
        schedule_type="D",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0014_schedule_allocation_status_check'),
        ('django_q', '__latest__'),
    ]

    operations = [
        migrations.RunPython(schedule_check_quota_consistency)
    ]
