# Generated by Django 4.2.11 on 2026-02-04 17:08

from django.db import migrations


def create_schedule(apps, schema_editor):
    """Create a daily schedule for checking expired allocations and setting quota to zero."""
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.get_or_create(
        func="imperial_coldfront_plugin.tasks.expires_allocations_gpfs_quota_check",
        defaults={
            "name": "Expired Allocations GPFS Quota Check",
            "schedule_type": Schedule.DAILY,
            "repeats": -1,
        },
    )


def delete_schedule(apps, schema_editor):
    """Remove the expired allocations quota check schedule."""
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.filter(
        func="imperial_coldfront_plugin.tasks.expires_allocations_gpfs_quota_check"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0014_schedule_allocation_status_check'),
        ('django_q', '0014_schedule_cluster'),
    ]

    operations = [
        migrations.RunPython(create_schedule, delete_schedule),
    ]
