# Generated by Django 4.2.11 on 2026-03-12 11:52

from django.db import migrations

def schedule_unlink_expired_filesets(apps, schema_editor):
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.update_or_create(
        name="Unlink GPFS filesets for expired RDF allocations",
        func="imperial_coldfront_plugin.tasks.unlink_expired_allocation_filesets",
        schedule_type="D",
    )

class Migration(migrations.Migration):
    dependencies = [
        ("imperial_coldfront_plugin", "0015_schedule_check_quota_consistency"),
        ("django_q", "__latest__"),
    ]

    operations = [
        migrations.RunPython(schedule_unlink_expired_filesets),
    ]
