# Generated by Django 4.2.11 on 2026-03-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0015_schedule_check_quota_consistency'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='authoriser',
            field=models.CharField(default='', max_length=255),
        ),
    ]
