# Generated by Django 4.2.11 on 2026-03-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20230406_1133'),
        ("allocation", "0005_auto_20211117_1413"),
        ('imperial_coldfront_plugin', '0015_schedule_check_quota_consistency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICLProject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.project',),
        ),
        migrations.CreateModel(
            name='RDFAllocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('allocation.allocation',),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imperial_coldfront_plugin.iclproject'),
        ),
    ]
