# Generated by Django 4.2.11 on 2026-03-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_historicalproject_options_and_more'),
        ('allocation', '0006_alter_historicalallocation_options_and_more'),
        ('imperial_coldfront_plugin', '0015_schedule_check_quota_consistency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICLProject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.project',),
        ),
        migrations.CreateModel(
            name='RDFAllocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('allocation.allocation',),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imperial_coldfront_plugin.iclproject'),
        ),
    ]
