# Generated by Django 4.2.11 on 2026-03-18 16:44

from django.db import migrations


def add_hx2_hx3_resources(apps, schema_editor):
    Resource = apps.get_model("resource", "Resource")
    ResourceType = apps.get_model("resource", "ResourceType")

    storage_resource_type, _ = ResourceType.objects.get_or_create(
        name="Cluster",
        defaults=dict(description="Cluster servers"),
    )
    Resource.objects.get_or_create(
        name="HX2",
        defaults=dict(
            description="Computer cluster associated with a research group on HX2.",
            is_allocatable=True,
            is_available=True,
            is_public=True,
            requires_payment=False,
            resource_type=storage_resource_type,
        ),
    )
    Resource.objects.get_or_create(
        name="HX3",
        defaults=dict(
            description="Compute cluster associated with a research group on HX3.",
            is_allocatable=True,
            is_available=True,
            is_public=True,
            requires_payment=False,
            resource_type=storage_resource_type,
        ),
    )

class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0017_iclproject_rdfallocation_and_more'),
    ]

    operations = [
        migrations.RunPython(add_hx2_hx3_resources),
    ]
