# Generated by Django 4.2.11 on 2026-03-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("allocation", "0005_auto_20211117_1413"),
        ('imperial_coldfront_plugin', '0018_add_hx2_hx3_resources'),
    ]

    operations = [
        migrations.CreateModel(
            name='HX2Allocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('allocation.allocation',),
        ),
    ]
