# Generated by Django 4.2.11 on 2026-03-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0018_add_hx2_hx3_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='authoriser',
            field=models.CharField(default='', max_length=255),
        ),
    ]
