# Generated by Django 4.2.11 on 2026-03-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0019_hx2allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='authoriser',
            field=models.CharField(default='', max_length=255),
        ),
    ]
