# Generated by Django 4.2.11 on 2026-03-31 14:21

from django.db import migrations
import datetime
from django_q.tasks import schedule


def run_consistency_check(apps, schema_editor):
    """Schedule a task to run the consistency check."""
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.update_or_create(
        name="HX2 and LDAP consistency check",
        func="imperial_coldfront_plugin.tasks.check_hx2_ldap_consistency",
        schedule_type="D",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0020_credittransaction_authoriser'),
        ('django_q', '0014_schedule_cluster'),
    ]

    operations = [
        migrations.RunPython(run_consistency_check),
    ]
