# Generated by Django 4.2.11 on 2026-06-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0022_rename_ldap_consistency_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('STG', 'Storage'), ('DON', 'Donation'), ('OTH', 'Other')], default='OTH', max_length=20),
        ),
    ]
