# Generated by Django 4.2.11 on 2026-07-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0023_credittransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('STG', 'Storage'), ('DON', 'Donation'), ('CRD', 'Credit'), ('OTH', 'Other')], default='OTH', max_length=20),
        ),
    ]
