# Generated by Django 4.2.11 on 2026-08-21 14:17

from django.db import migrations

def update_consistency_check(apps, schema_editor):
    """Update the scheduled task for LDAP consistency checks to be more general."""
    Schedule = apps.get_model("django_q", "Schedule")

    Schedule.objects.get(func="imperial_coldfront_plugin.tasks.check_hx2_ldap_consistency").delete()
    Schedule.objects.update_or_create(
        name="HX2 LDAP consistency check",
        func="imperial_coldfront_plugin.tasks.check_hx_ldap_consistency",
        schedule_type="D",
        args=["hx2"],
    )
    Schedule.objects.update_or_create(
        name="HX3 LDAP consistency check",
        func="imperial_coldfront_plugin.tasks.check_hx_ldap_consistency",
        schedule_type="D",
        args=["hx3"],
    )

class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0024_alter_credittransaction_transaction_type'),
    ]

    operations = [
        migrations.RunPython(update_consistency_check),
    ]
