# Generated by Django 4.2.11 on 2026-07-21 11:52

from django.db import migrations


def schedule_gpfs_consistency_check(apps, schema_editor):
    """Adds scheduled task to check for GPFS filesets missing in Coldfront."""
    Schedule = apps.get_model("django_q", "Schedule")
    Schedule.objects.update_or_create(
        name="Check for GPFS filesets missing in Coldfront",
        func="imperial_coldfront_plugin.tasks.check_gpfs_consistency",
        schedule_type="D",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('imperial_coldfront_plugin', '0024_alter_credittransaction_transaction_type'),
        ('django_q', '__latest__'),
    ]

    operations = [
        migrations.RunPython(schedule_gpfs_consistency_check),
    ]
