# Generated by Django 4.2.11 on 2026-08-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0005_auto_20211117_1413'),
        ('imperial_coldfront_plugin', '0025_generalise_hx2_ldap_consistency_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HX2Allocation',
        ),
        migrations.CreateModel(
            name='HXAllocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('allocation.allocation',),
        ),
    ]
